# -*- coding: utf-8 -*-
"""Grocery Store.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpgdRtzuICleooWfsXCzGbtPw1XaoxsU

#Grocery Store Checkout System Using List
"""

#step1:Available products and prices
#define a new list products for listing the grocery item
products= ["Vegetable","Bread","Butter","Jam"]
cost = [100.50,35.75,156.25,80.75]

#Define Cart : EMPTY
cart = []

#Display the menu
def show_product():
  print("\n The Available Products")
  for i, item in enumerate(products):
    print(f"{i+1} - {item} - {cost[i]}")
show_product()

#Add item to cart
def add_to_cart():
  show_product()
  choice = int(input("Enter the product number to add:"))-1
  if 0 <= choice <len(products):#condition to check whether the item is available

#Remove item from cart
def remove_from_cart():
  if not cart:
    print("Cart is empty!")
    return
  show_cart()
  choice = int(input("Enter item number in cart to remove:"))
  if 0<= choice <len(cart):
    removed_item = cart.pop(choice)
    print(f"{products[removed_item]} removed from the cart")
  else